package com.example.lansiacare.ui.medicalnotes

import android.content.Intent
import android.os.Bundle
import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import androidx.fragment.app.DialogFragment
import com.example.lansiacare.utils.DateUtils
import com.example.lansiacare.data.entities.MedicalNote
import com.example.lansiacare.databinding.DialogMedicalNoteDetailBinding

class MedicalNoteDetailDialog : DialogFragment() {

    private var _binding: DialogMedicalNoteDetailBinding? = null
    private val binding get() = _binding!!

    private lateinit var medicalNote: MedicalNote

    companion object {
        private const val ARG_MEDICAL_NOTE = "medical_note"

        fun newInstance(medicalNote: MedicalNote): MedicalNoteDetailDialog {
            val dialog = MedicalNoteDetailDialog()
            dialog.medicalNote = medicalNote
            return dialog
        }
    }

    override fun onCreateView(
        inflater: LayoutInflater,
        container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View {
        _binding = DialogMedicalNoteDetailBinding.inflate(inflater, container, false)
        return binding.root
    }

    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)

        setupDialog()
        populateData()
        setupClickListeners()
    }

    private fun setupDialog() {
        dialog?.window?.setLayout(
            (resources.displayMetrics.widthPixels * 0.95).toInt(),
            (resources.displayMetrics.heightPixels * 0.8).toInt()
        )
    }

    private fun populateData() {
        binding.apply {
            tvNoteTitle.text = medicalNote.title
            tvNoteDate.text = "Tanggal: ${DateUtils.formatDate(medicalNote.visitDate)}"

            if (medicalNote.doctorName.isNotEmpty()) {
                tvDoctorName.text = "Dokter: Dr. ${medicalNote.doctorName}"
                tvDoctorName.visibility = View.VISIBLE
            } else {
                tvDoctorName.visibility = View.GONE
            }

            if (medicalNote.hospital.isNotEmpty()) {
                tvHospitalName.text = "Rumah Sakit: ${medicalNote.hospital}"
                tvHospitalName.visibility = View.VISIBLE
            } else {
                tvHospitalName.visibility = View.GONE
            }

            tvNoteDescription.text = medicalNote.description
            tvCreatedDate.text = "Dibuat: ${DateUtils.formatDateTime(medicalNote.createdAt)}"
        }
    }

    private fun setupClickListeners() {
        binding.btnClose.setOnClickListener {
            dismiss()
        }

        binding.btnShare.setOnClickListener {
            shareNote()
        }
    }

    private fun shareNote() {
        val noteContent = buildString {
            appendLine("=== CATATAN MEDIS ===")
            appendLine()
            appendLine("Judul: ${medicalNote.title}")
            appendLine("Tanggal Kunjungan: ${DateUtils.formatDate(medicalNote.visitDate)}")

            if (medicalNote.doctorName.isNotEmpty()) {
                appendLine("Dokter: Dr. ${medicalNote.doctorName}")
            }

            if (medicalNote.hospital.isNotEmpty()) {
                appendLine("Rumah Sakit: ${medicalNote.hospital}")
            }

            appendLine()
            appendLine("Deskripsi:")
            appendLine(medicalNote.description)
            appendLine()
            appendLine("Generated by Lansia Care App")
        }

        val shareIntent = Intent(Intent.ACTION_SEND)
        shareIntent.type = "text/plain"
        shareIntent.putExtra(Intent.EXTRA_TEXT, noteContent)
        shareIntent.putExtra(Intent.EXTRA_SUBJECT, "Catatan Medis: ${medicalNote.title}")

        startActivity(Intent.createChooser(shareIntent, "Bagikan Catatan Medis"))
    }

    override fun onStart() {
        super.onStart()
        dialog?.window?.setLayout(
            (resources.displayMetrics.widthPixels * 0.95).toInt(),
            ViewGroup.LayoutParams.WRAP_CONTENT
        )
    }

    override fun onDestroyView() {
        super.onDestroyView()
        _binding = null
    }
}