package com.example.lansiacare.ui.emergency

import android.os.Bundle
import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import androidx.fragment.app.DialogFragment
import android.content.Intent
import androidx.lifecycle.ViewModelProvider
import com.example.lansiacare.utils.ViewModelFactory
import com.example.lansiacare.utils.UserPreferences
import com.example.lansiacare.data.database.AppDatabase
import com.example.lansiacare.data.repository.MedicalNoteRepository
import com.example.lansiacare.data.repository.UserRepository
import com.example.lansiacare.data.repository.MedicationRepository
import com.example.lansiacare.data.repository.HealthRecordRepository
import com.example.lansiacare.databinding.DialogMedicalInfoBinding


class MedicalInfoDialog : DialogFragment() {

    private var _binding: DialogMedicalInfoBinding? = null
    private val binding get() = _binding!!

    private lateinit var emergencyViewModel: EmergencyViewModel

    companion object {
        fun newInstance(): MedicalInfoDialog {
            return MedicalInfoDialog()
        }
    }

    override fun onCreateView(
        inflater: LayoutInflater,
        container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View {
        _binding = DialogMedicalInfoBinding.inflate(inflater, container, false)
        return binding.root
    }

    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)

        setupViewModel()
        loadMedicalInfo()
        setupClickListeners()
    }

    private fun setupViewModel() {
        val database = AppDatabase.getDatabase(requireContext())
        val userPreferences = UserPreferences(requireContext())

        val viewModelFactory = ViewModelFactory(
            UserRepository(database.userDao()),
            MedicationRepository(database.medicationDao()),
            HealthRecordRepository(database.healthRecordDao()),
            MedicalNoteRepository(database.medicalNoteDao()),
            userPreferences
        )

        emergencyViewModel = ViewModelProvider(this, viewModelFactory)[EmergencyViewModel::class.java]
    }

    private fun loadMedicalInfo() {
        // Load current medications and recent health records
        val userEmail = UserPreferences(requireContext()).getUserEmail() ?: ""

        // This would typically load from database
        binding.apply {
            tvCurrentMedications.text = "• Paracetamol 500mg - 2x sehari\n• Vitamin D - 1x sehari\n• Aspirin 100mg - 1x sehari"
            tvAllergies.text = "• Tidak ada alergi obat yang diketahui"
            tvMedicalConditions.text = "• Hipertensi\n• Diabetes Tipe 2"
            tvEmergencyInstructions.text = "• Hubungi dokter keluarga: Dr. Budi (081234567890)\n• Rumah sakit terdekat: RS Siloam (5 km)\n• Jika pingsan, periksa gula darah segera"
        }
    }

    private fun setupClickListeners() {
        binding.btnClose.setOnClickListener {
            dismiss()
        }

        binding.btnShareInfo.setOnClickListener {
            shareMedicalInfo()
        }
    }

    private fun shareMedicalInfo() {
        val medicalInfo = buildString {
            appendLine("=== INFORMASI MEDIS DARURAT ===")
            appendLine()
            appendLine("Nama: ${UserPreferences(requireContext()).getUserName()}")
            appendLine("Obat yang Sedang Dikonsumsi:")
            appendLine(binding.tvCurrentMedications.text)
            appendLine()
            appendLine("Alergi:")
            appendLine(binding.tvAllergies.text)
            appendLine()
            appendLine("Kondisi Medis:")
            appendLine(binding.tvMedicalConditions.text)
            appendLine()
            appendLine("Instruksi Darurat:")
            appendLine(binding.tvEmergencyInstructions.text)
            appendLine()
            appendLine("Generated by Lansia Care App")
        }

        val shareIntent = Intent(Intent.ACTION_SEND)
        shareIntent.type = "text/plain"
        shareIntent.putExtra(Intent.EXTRA_TEXT, medicalInfo)
        shareIntent.putExtra(Intent.EXTRA_SUBJECT, "Informasi Medis Darurat")

        startActivity(Intent.createChooser(shareIntent, "Bagikan Informasi Medis"))
    }

    override fun onStart() {
        super.onStart()
        dialog?.window?.setLayout(
            (resources.displayMetrics.widthPixels * 0.9).toInt(),
            ViewGroup.LayoutParams.WRAP_CONTENT
        )
    }

    override fun onDestroyView() {
        super.onDestroyView()
        _binding = null
    }
}